language: node_js
sudo: false
node_js:
  - 12.0.0
addons:
  chrome: stable

cache: false

install:
  - npm ci

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT .tmp/coverage/lcov.info
